#! /bin/sh -x
#
# flash_policyd  This starts and stops the Flash socket policy server
#
# chkconfig: 345 50 50
# description: The Flash socket policy server
#
# processname: /usr/local/bin/flash_policy
# config: /etc/flash/pconfig.txt
# Policy File: /etc/flash/policy.txt

. /etc/init.d/functions

#####################
#BEGIN CONFIG SECTION

core=flash_policyd

#Location of daemon
prog=/usr/local/bin/${core}

#Location of socket policy file
policy=/etc/flash/policy.txt

#Pid file to track start/stop of process
pidfile=/var/run/${core}.pid

logfile=/dev/null

#END CONFIG SECTION
#####################


[ "$NETWORKING" = "no" ] && exit 0
[ -f "$prog" ] || exit 1
[ -f "$policy" ] || exit 1

RETVAL=0

start() {
    echo -n "Starting ${core}: "

#  flash_policy [-f policyfile] [-p port] [-u username] [-c chrootdir]
#  Defaults: -f /etc/flash/policy.txt, -p 843


    $prog -d $pidfile 2>>"$logfile"  
    RETVAL=$?
    #echo $! > $pidfile
    [ "$RETVAL" -eq 0 ] && success $"$base startup" || failure $"$base startup"
    echo
    touch /var/lock/subsys/${core}
}

stop() {
    echo -n "Stopping flash_policy: "
    killproc -p $pidfile "$prog"
    RETVAL=$?
    echo
    rm -f /var/lock/subsys/${core}
}

restart() {
    stop
    start
}

condrestart() {
    [ -e /var/lock/subsys/${core} ] && restart
}
    
case "$1" in
    start)
    start
    ;;
    stop)
    stop
    ;;
    status)
    status -p "$pidfile" "$prog"
    ;;
    restart|reload)
    restart
    ;;
    condrestart)
    condrestart
    ;;
    *)
    echo "Usage: ${core}{start|stop|status|restart}"
    RETVAL=1
esac

exit $RETVAL
